Repository cert-manager/google-cas-issuer, pull requests merged in 2021-01, with the labels that each got.

#10 Typo fixes in the Readme
  README.md
Labels: lgtm, size/XS

#9 Fix for GoogleCASIssuer.cas-issuer.jetstack.io not found due to be empty
  pkg/controller/certificaterequest/certificaterequest_controller.go
Labels: lgtm, size/XS

#18 Add Github Action to build docker image
  .github/workflows/docker.yml
  Dockerfile
Labels: size/M

#17 WIP: Refactor Issuer to be stateless and behave nicely on misconfiguration
  .github/workflows/docker.yml
  Dockerfile
  api/v1alpha1/googlecasclusterissuer_types.go
  api/v1alpha1/googlecasissuer_types.go
  cmd/root.go
  config/crd/bases/cas-issuer.jetstack.io_googlecasclusterissuers.yaml
  config/crd/bases/cas-issuer.jetstack.io_googlecasissuers.yaml
  config/crd/bases/issuers.jetstack.io_googlecasclusterissuers.yaml
  config/crd/bases/issuers.jetstack.io_googlecasissuers.yaml
  pkg/cas/README.md
  pkg/cas/cas.go
  pkg/cas/cas_test.go
  pkg/cas/certificate.go
  pkg/cas/certificateauthority.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/issuer/googlecasclusterissuer_controller.go
  pkg/controller/issuer/googlecasissuer_controller.go
Labels: do-not-merge/work-in-progress, size/XXL

#16 Pass the main signal handler context to controllers
  .github/workflows/docker.yml
  Dockerfile
  api/v1alpha1/googlecasclusterissuer_types.go
  api/v1alpha1/googlecasissuer_types.go
  cmd/cmd.go
  cmd/root.go
  config/crd/bases/cas-issuer.jetstack.io_googlecasclusterissuers.yaml
  config/crd/bases/cas-issuer.jetstack.io_googlecasissuers.yaml
  config/crd/bases/issuers.jetstack.io_googlecasclusterissuers.yaml
  config/crd/bases/issuers.jetstack.io_googlecasissuers.yaml
  go.mod
  go.sum
  pkg/cas/README.md
  pkg/cas/cas.go
  pkg/cas/cas_test.go
  pkg/cas/certificate.go
  pkg/cas/certificateauthority.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/issuer/googlecasclusterissuer_controller.go
  pkg/controller/issuer/googlecasissuer_controller.go
  pkg/controller/suite_test.go
Labels: size/XXL

#19 Automatic release pipelines
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  Dockerfile
  Makefile
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: lgtm, size/L

#20 Add RBAC for working leader election
  Makefile
  config/default/kustomization.yaml
  config/rbac/leader_election_role.yaml
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/issuer/googlecasissuer_controller.go
Labels: lgtm, size/S
