Repository cert-manager/google-cas-issuer, pull requests merged in 2021-06, with the labels that each got.

#36 Update the CAS Issuer for the GA release of Google Certificate Authority Service
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  Makefile
  README.md
  api/v1beta1/googlecasclusterissuer_types.go
  api/v1beta1/googlecasissuer_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/cmd.go
  cmd/root.go
  config/crd/bases/cas-issuer.jetstack.io_googlecasclusterissuers.yaml
  config/crd/bases/cas-issuer.jetstack.io_googlecasissuers.yaml
  config/manager/manager.yaml
  deploy/google-cas-issuer.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/casutil/ca.go
  hack/casutil/capool.go
  hack/casutil/casutil.go
  hack/casutil/certificates.go
  main.go
  pkg/cas/cas.go
  pkg/cas/cas_test.go
  pkg/controller/certificaterequest/certificaterequest_controller.go
  pkg/controller/issuer/googlecasissuer_controller.go
  pkg/controller/issuer/googlecasissuer_controller_test.go
  pkg/controller/suite_test.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/config/config.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/helper.go
  test/e2e/suite/issuers/google-sa
  test/e2e/suite/issuers/issuers.go
  test/e2e/suite/suite.go
  test/e2e/suite/validation/validation.go
  test/e2e/util/util.go
Labels: size/XXL

#38 Tidy the workload identity section
  README.md
Labels: size/S

#40 Ensure certificates end in exactly one newline
  pkg/cas/cas.go
  pkg/cas/cas_test.go
Labels: size/L

#42 Stable leader election
  README.md
  cmd/root.go
  pkg/cas/cas_test.go
  test/e2e/suite/issuers/issuers.go
  test/e2e/suite/leaderelection/leaderelection.go
  test/e2e/suite/suite.go
  test/e2e/suite/validation/validation.go
Labels: size/L

#45 Change the pool for e2e tests
  Makefile
Labels: lgtm, size/XS
