Repository cert-manager/google-cas-issuer, pull requests merged in 2022-12, with the labels that each got.

#86 Helm Chart fixes
  deploy/charts/google-cas-issuer/Chart.yaml
  deploy/charts/google-cas-issuer/README.md
  deploy/charts/google-cas-issuer/templates/deployment.yaml
  deploy/charts/google-cas-issuer/templates/serviceaccount.yaml
  deploy/charts/google-cas-issuer/values.yaml
Labels: lgtm, size/S

#93 fix README after #86, trigger tests before release
  deploy/charts/google-cas-issuer/README.md
  deploy/charts/google-cas-issuer/templates/serviceaccount.yaml
Labels: size/XS

#95 Bump default image version in helm chart
  deploy/charts/google-cas-issuer/README.md
  deploy/charts/google-cas-issuer/values.yaml
Labels: lgtm, size/XS
