Repository cert-manager/google-cas-issuer, pull requests merged in 2025-08, with the labels that each got.

#290 Update vulnerable dependency reported by govulncheck
  go.mod
  go.sum
Labels: lgtm, size/XS, dco-signoff: yes, approved

#291 Update readme to add missing step
  README.md
Labels: lgtm, size/S, dco-signoff: yes, approved

#299 Manual self upgrade
  .github/dependabot.yaml
  .github/renovate.json5
  .github/workflows/renovate.yaml
  .gitignore
  deploy/charts/google-cas-issuer/templates/crd-cas-issuer.jetstack.io_googlecasclusterissuers.yaml
  deploy/charts/google-cas-issuer/templates/crd-cas-issuer.jetstack.io_googlecasissuers.yaml
  klone.yaml
  make/_shared/go/01_mod.mk
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base-dependabot/.github/renovate.json5
  make/_shared/repository-base/base-dependabot/.github/workflows/renovate.yaml
Labels: lgtm, size/L, dco-signoff: yes, approved
